name: Secrets

on: workflow_dispatch

jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWORD: ${{ vars.PASSWORD }}
    steps:
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
